---

version: 0.2

phases:
  install:
    commands:
      - echo "Entering Build Phase "
    runtime-versions:
      php: 7.4
  build:
    commands:
      - echo "********BUILD PHASE CF PACKAGING  **********"
      - "aws cloudformation package --template-file StaticWebServer.yml --s3-bucket staticwebserverbucket --output-template-file packaged-webserver.yaml --region us-east-1"

artifacts:
  discard-paths: true
  files:
    - packaged-webserver.yaml
  


